import 'package:flutter/material.dart';

void main() {
  runApp(const TestScreen());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class TestScreen extends StatelessWidget {
  const TestScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone1314Lion(),
        ]),
      ),
    );
  }
}

class Iphone1314Lion extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFF6F9F6),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: MediaQuery.of(context).size.width,
                  height: 844,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/images/Animals/Background.png"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 46,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.only(
                    top: 2,
                    left: 6,
                    right: 6.22,
                    bottom: 2,
                  ),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 49,
                child: Container(
                  width: 350,
                  height: 735,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 20,
                        top: 281,
                        child: Container(
                          width: MediaQuery.of(context).size.width-80,
                          height: 454,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 25,
                                child: Container(
                                  width: MediaQuery.of(context).size.width-80,
                                  height: 429,
                                  decoration: ShapeDecoration(
                                    color: Color(0xD3D8D8D8),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 238,
                                top: 0,
                                child: Container(
                                  width: 50,
                                  height: 50,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 50,
                                          height: 50,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFF414141),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 10,
                                        top: 10,
                                        child: Container(
                                          width: 30,
                                          height: 30,
                                          padding: const EdgeInsets.all(4),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 317,
                        child: Text(
                          'Lion',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 347,
                        child: Text(
                          'Class: Reptilia',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.6000000238418579),
                            fontSize: 12,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 386,
                        child: SizedBox(
                          width: 284,
                          height: 319,
                          child: Text(
                            'The lion, Panthera leo, is a large cat native to Africa and India, known for its muscular body, short head, and distinctive mane in males. Lions live in social groups called prides, consisting of a few males, related females, and cubs. They typically hunt together, preying on large ungulates. Lions are apex predators but may scavenge opportunistically. Their habitat includes grasslands, savannahs, and shrublands. Despite their cultural significance, lion populations have declined significantly due to habitat loss and conflicts with humans. Lions are listed as Vulnerable by the IUCN. They have been depicted widely in art, literature, and culture throughout history.',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.800000011920929),
                              fontSize: 13,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 350,
                          height: 226.37,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: AssetImage("assets/images/Animals/lion.png"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}