import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone13141stScreen(),
        ]),
      ),
    );
  }
}

class Iphone13141stScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFF6F9F6),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 133,
                top: 360,
                child: Container(
                  width: 123,
                  height: 123,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("assets/images/getstarted/Untitled1.png"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 134,
                child: SizedBox(
                  width: 213,
                  height: 61,
                  child: Text(
                    'MuseuLink',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF000000),
                      fontSize: 30,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w900,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 74,
                top: 215,
                child: SizedBox(
                  width: 241,
                  child: Text(
                    'Sculpting the Future of Cultural Exploration',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF7A9B79),
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w800,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 94,
                top: 636,
                child: Text(
                  'Forgot your password? Click here.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF86A9AC),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    decoration: TextDecoration.underline,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 783,
                child: Text(
                  "Don't have an account yet?  Sign up!",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF86A9AC),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    decoration: TextDecoration.underline,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 570,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 80, vertical: 10),
                  decoration: ShapeDecoration(
                    color: Color(0xFF7A9B79),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 15,
                        offset: Offset(2, 5),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Log In',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}